server:
  port: 8081

araujo:
  client:
    address:
      url: http://localhost:8002/addresses

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: cleanarch